insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Shrek', 4.0, 76, 2005);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Score: A Hockey Musical', 2.0, 63, 2011);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Reeker', 4.4, 82, 2002);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Real Fiction (Shilje sanghwang)', 3.0, 81, 2001);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Petals on the Wind', 1.1, 61, 2007);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Tyler Perry''s Why Did I Get Married Too?', 4.2, 63, 1995);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Haunted Echoes', 3.2, 55, 2001);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Adventures of Priscilla, Queen of the Desert, The', 2.3, 81, 1995);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Loaf and Camouflage', 2.4, 73, 1992);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Blood Money', 1.7, 59, 2002);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Airplane II: The Sequel', 2.2, 100, 1959);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('All of Me', 2.7, 95, 2008);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Ward 13', 4.5, 60, 1988);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Nightwing', 4.8, 85, 2006);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('33 Postcards', 3.9, 78, 1997);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Exit', 3.2, 66, 2001);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Young Guns', 1.0, 79, 1999);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('This Ain''t California', 2.5, 71, 2013);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Hearts of Darkness: A Filmmakers Apocalypse', 1.5, 81, 1990);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Machine Gun Preacher', 1.5, 100, 1985);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Wuthering Heights', 2.3, 68, 1995);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Funny Games U.S.', 3.0, 75, 2010);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Rope', 4.5, 74, 1998);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Australian Atomic Confessions', 1.2, 66, 2012);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Capturing the Friedmans', 2.9, 76, 2012);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Aaltra', 3.1, 76, 2007);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Mike Birbiglia: My Girlfriend''s Boyfriend', 1.6, 90, 1999);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Home Movie', 3.2, 60, 2001);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Dr. Seuss'' The Lorax', 2.7, 56, 2006);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Winter Light (Nattvardsgästerna)', 2.6, 98, 2001);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Irony of Fate, or Enjoy Your Bath! (Ironiya sudby, ili S legkim parom!)', 1.8, 62, 2012);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('The Gunman', 4.9, 54, 1969);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Sneakers', 3.6, 57, 1999);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Card Subject To Change', 3.2, 85, 2002);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Take, The', 3.6, 51, 1999);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Frankenstein Meets the Wolf Man', 1.4, 77, 1993);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Those Daring Young Men in Their Jaunty Jalopies', 3.2, 70, 2000);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Free Soul, A', 3.0, 99, 2000);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Welcome to the Jungle', 4.6, 74, 2004);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Secret Life of Walter Mitty, The', 4.5, 100, 2008);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Meltdown (Shu dan long wei)', 2.7, 73, 2012);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Judy Berlin', 4.8, 66, 2000);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Saving General Yang', 4.3, 51, 2013);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Criminal, The (a.k.a. Concrete Jungle)', 2.0, 79, 2003);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('29th Street', 3.7, 64, 2002);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Role/Play', 1.9, 52, 1987);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Alan & Naomi', 1.6, 58, 2010);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Brotherhood of Death', 3.9, 60, 1987);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Violeta Went to Heaven (Violeta se fue a los cielos)', 4.9, 59, 1999);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Where Eagles Dare', 3.4, 94, 2008);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('66 Scenes From America', 1.3, 55, 2004);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Carmen', 2.7, 82, 2009);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Clubland (a.k.a. Introducing the Dwights)', 1.2, 59, 2004);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Key of Life (Kagi-dorobô no mesoddo)', 3.0, 70, 1995);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Incident at Blood Pass (Machibuse) (Ambush)', 1.2, 54, 2005);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Lady Vanishes, The', 3.3, 66, 2011);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Pecker', 4.0, 78, 2011);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Star Wars: Threads of Destiny', 2.5, 92, 2003);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Beginners', 1.6, 93, 1994);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Inheritors, The (Siebtelbauern, Die)', 3.1, 100, 1997);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Ace Attorney (Gyakuten saiban)', 2.8, 82, 2005);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Goodbye to Language 3D', 2.1, 80, 1997);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Redirected', 3.7, 99, 2001);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Bounty Killer', 2.8, 71, 2006);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Thick as Thieves (a.k.a. Code, The)', 1.5, 78, 1999);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Mahogany', 4.7, 53, 2002);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('I Am Trying to Break Your Heart', 5.0, 69, 2012);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Peter Pan', 1.1, 73, 1998);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('And the Ship Sails On (E la nave va)', 3.7, 93, 2003);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('What Happened Was...', 1.4, 57, 2011);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Shit Year', 1.3, 64, 1993);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Little Secrets', 4.4, 80, 2010);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Yu-Gi-Oh!', 4.1, 81, 2000);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Merry-Go-Round', 1.1, 94, 1999);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Zincirbozan', 4.1, 62, 1995);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Konopielka', 4.4, 96, 2000);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Are We Done Yet?', 4.6, 67, 1993);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Cesar Chavez', 3.3, 89, 2005);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('The Evictors', 1.7, 50, 1982);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Amazing Journey: The Story of The Who', 3.0, 68, 2009);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Border Radio', 1.8, 51, 2008);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('High Test Girls', 4.1, 54, 2007);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Destry Rides Again', 3.5, 79, 1999);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Proxy', 3.0, 94, 1986);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Perez Family, The', 1.5, 58, 2012);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('He Was a Quiet Man', 2.3, 66, 2000);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Life is a Bed of Roses (Vie est un roman, La)', 2.2, 88, 1996);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Schizopolis', 1.9, 71, 2006);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Conspirator, The', 2.0, 51, 2003);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Thin Man, The', 2.7, 66, 1998);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Jack the Giant Slayer', 2.3, 52, 2010);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Nancy Drew', 1.8, 56, 1995);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Smurfs, The', 4.6, 55, 1985);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Bernie', 2.2, 52, 1995);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Legend of Lobo, The', 2.7, 58, 2000);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('First Cousin Once Removed', 1.8, 60, 1997);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Sweet Land', 1.0, 95, 2004);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Jewel of the Nile, The', 4.0, 97, 2000);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Something New', 2.1, 88, 1996);
insert into Peliculas (Titulo, Puntuacion, Rating, Fecha_Publicacion) values ('Sergio', 1.2, 72, 1995);